<?php

putenv('DISPLAY_ERRORS_DETAILS=' . true);

putenv('MARKET_MANAGEMENT_HOST=');
putenv('MARKET_MANAGEMENT_DBNAME=');
putenv('MARKET_MANAGEMENT_USER=');
putenv('MARKET_MANAGEMENT_PASSWORD=');
putenv('MARKET_MANAGEMENT_PORT=');